#!/bin/sh

mv "4dwarrio.png" "4-D Warriors.png"
mv "280zzzap.png" "280Z-ZZAP.png"
mv "1941.png" "1941  Counter Attack -World 900227-.png"
mv "1943kai.png" "1943 Kai Midway Kaisen.png"
mv "1943kai.png" "1943 Midway Kaisen.png"
mv "1943b.png" "1943 The Battle of Midway Mark II.png"
mv "1943b.png" "1943 The Battle of Midway.png"
mv "alibaba.png" "Alibaba 40 Thieves.png"
mv "alienar.png" "Alien Arena.png"
mv "maze.png" "Amazing Maze.png"
mv "amidar.png" "Amidar.png"
mv "anteater.png" "Anteater.png"
mv "arkanoid.png" "Arkanoid (Japan).png"
mv "arkanoid.png" "Arkanoid (unl.lives, slower).png"
mv "arkanoid.png" "Arkanoid (Unlimited Lives).png"
mv "arkanoid.png" "Arkanoid (US).png"
mv "arkanoid.png" "Arkanoid (World).png"
mv "armorcar.png" "Armored Car.png"
mv "astdelux1.png" "Asteroids Deluxe.png"
mv "asteroid.png" "Asteroids.png"
mv "attackfc.png" "Attack Force.png"
mv "azurian.png" "Azurian Attack.png"
mv "bagman.png" "Bagman.png"
mv "ballbomb.png" "Balloon Bomber.png"
mv "battlntsj.png" "Battle of Atlantis.png"
mv "beastf.png" "Beastie Feastie.png"
mv "berzerk.png" "Berzerk.png"
mv "bigkong.png" "Big Kong.png"
mv "bilyard.png" "Billiard.png"
mv "bionicc.png" "Bionic Commando.png"
mv "birdiy.png" "Birdiy.png"
mv "blkhole.png" "Black Hole.png"
mv "blktiger.png" "Black Tiger.png"
mv "bwidow.png" "Black Widow.png"
mv "blueshrk.png" "Blue Shark.png"
mv "bombjack.png" "Bomb Jack.png"
mv "boothill.png" "Boot Hill.png"
mv "botanic.png" "Botanic.png"
mv "breakout.png" "Breakout.png"
mv "bublbobl.png" "Bubble Bobble (Japan, Ver 0.1).png"
mv "bubbles.png" "Bubbles.png"
mv "bullfgt.png" "Bullfight.png"
mv "btime.png" "Burger Time.png"
mv "brubber.png" "BurningRubber.png"
mv "dinopic.png" "Cadillacs and Dinosaurs (World 930201).png"
mv "calipso.png" "Calipso.png"
mv "canyon.png" "Canyon Bomber.png"
mv "captcommb.png" "Captain Commando -World 911202-.png"
mv "cawingbl.png" "Carrier Air Wing -World 901012-.png"
mv "catacomb.png" "Catacomb.png"
mv "centiped.png" "Centipede (revision 4).png"
mv "centiped.png" "Centipede.png"
mv "clowns.png" "Clowns.png"
mv "colony7.png" "Colony 7.png"
mv "combatscb.png" "Combat School Joystick.png"
mv "commando.png" "Commando.png"
mv "contra.png" "Contra (US 3).png"
mv "cavenger.png" "Cosmic Avenger.png"
mv "cosmo.png" "Cosmo.png"
mv "crater.png" "Crater Raider.png"
mv "crbaloon.png" "Crazy Balloon.png"
mv "ccboot.png" "Crazy Climber.png"
mv "ckong.png" "Crazy Kong (Orca bootleg).png"
mv "ckongpt2.png" "Crazy Kong Part II.png"
mv "ckong.png" "Crazy Kong.png"
mv "crushs.png" "Crush Roller.png"
mv "daimakai.png" "Daimakaimura -Japan Resale Ver.-.png"
mv "daimakai.png" "Daimakaimura -Japan-.png"
mv "darkplnt.png" "Dark Planet (no bkg).png"
mv "darkplnt.png" "Dark Planet.png"
mv "defender.png" "Defender.png"
mv "demoderb.png" "Demolition Derby.png"
mv "devilfsh.png" "Devil Fish.png"
mv "digdug.png" "Dig Dug.png"
mv "digdug2.png" "DigDug2.png"
mv "dotron.png" "Discs of Tron.png"
mv "ddonpach.png" "DoDonPachi (Arrange).png"
mv "ddonpach.png" "DoDonPachi (Japan).png"
mv "ddonpach.png" "DoDonPachi.png"
mv "domino.png" "Domino Man.png"
mv "dominos.png" "Dominos.png"
mv "dkong.png" "Donkey Kong (Spanish Crazy Kong bootleg).png"
mv "dkong3.png" "Donkey Kong 3 (bootleg).png"
mv "dkong3.png" "Donkey Kong 3.png"
mv "dkongjr.png" "Donkey Kong Junior.png"
mv "dkong.png" "Donkey Kong.png"
mv "dorodon.png" "Dorodon.png"
mv "ddragon2.png" "Double Dragon II - The Revenge.png"
mv "ddragon.png" "Double Dragon.png"
mv "dremshpr.png" "Dream Shopper.png"
mv "druaga.png" "Druaga.png"
mv "dynwar.png" "Dynasty Wars -USA, B-Board 89624B- -.png"
mv "eggor.png" "Eggor.png"
mv "ebases.png" "Extra Bases.png"
mv "eyes.png" "Eyes.png"
mv "f1dreamb.png" "F-1 Dream.png"
mv "ffight.png" "Final Fight -World, set 1-.png"
mv "flicky.png" "Flicky.png"
mv "foodf.png" "Food Fight.png"
mv "forgottn.png" "Forgotten Worlds -World, newer-.png"
mv "frenzy.png" "Frenzy.png"
mv "frogger.png" "Frogger (Konami Bugfixed).png"
mv "frogger.png" "Frogger.png"
mv "futspy.png" "Future Spy.png"
mv "galaga3.png" "Galaga 3 (GP3 rev. D).png"
mv "galaga.png" "Galaga.png"
mv "galaxian.png" "Galaxian.png"
mv "galxwars.png" "Galaxy Wars.png"
mv "ganbare.png" "Ganbare! Marine Kun -Japan 2K0411-.png"
mv "gaplus.png" "Gaplus (GP2 rev. B).png"
mv "gauntlets.png" "Gauntlet (rev 14).png"
mv "gaunt2g.png" "Gauntlet II.png"
mv "gemini.png" "Gemini Wing.png"
mv "gng.png" "Ghosts'n Goblins (JT).png"
mv "gng.png" "Ghouls'n Ghosts -patched-.png"
mv "gng.png" "Ghouls'n Ghosts -World-.png"
mv "gorf.png" "Gorf - Program 1.png"
mv "gorf.png" "Gorf - Speech.png"
mv "gorf.png" "Gorf.png"
mv "gorkans.png" "Gorkans.png"
mv "gorodki.png" "Gorodki.png"
mv "gravitar.png" "Gravitar.png"
mv "gberet.png" "Green Beret.png"
mv "gunfight.png" "Gun Fight.png"
mv "gunsmoke.png" "Gun Smoke.png"
mv "horizon.png" "Horizon.png"
mv "imsorry.png" "I'm Sorry.png"
mv "jin.png" "Jin.png"
mv "journey.png" "Journey.png"
mv "joust.png" "Joust.png"
mv "jumpshotp.png" "Jump Shot.png"
mv "kickman.png" "Kick-Man.png"
mv "kick.png" "Kick.png"
mv "kidniki.png" "Kid Niki - Radical Ninja.png"
mv "kingball.png" "King And Balloon.png"
mv "knightsja.png" "Knights of the Round -World 911127-.png"
mv "konek.png" "Konek Gorbunok.png"
mv "kroozr.png" "Kozmik Kroozr.png"
mv "kungfum.png" "Kung-Fu Master.png"
mv "ladybug.png" "Lady Bug.png"
mv "lagunar.png" "Laguna Racer.png"
mv "lwings.png" "Legendary Wings.png"
mv "lizwiz.png" "Lizard Wizard.png"
mv "ldrun2.png" "Lode Runner II - The Bungeling Strikes Back.png"
mv "ldrun3.png" "Lode Runner III - The Golden Labyrinth.png"
mv "ldrun4.png" "Lode Runner IV - Teikoku Karano Dasshutsu.png"
mv "ldrun.png" "Lode Runner.png"
mv "losttomb.png" "Lost Tomb.png"
mv "lunarbat.png" "Lunar Battle.png"
mv "llander.png" "Lunar Lander.png"
mv "lrescue.png" "Lunar Rescue.png"
mv "lupin3.png" "Lupin III.png"
mv "msword.png" "Magic Sword  Heroic Fantasy -World 900725-.png"
mv "mappy.png" "Mappy.png"
mv "mario.png" "Mario Bros.png"
mv "mars.png" "Mars.png"
mv "maxrpm.png" "Max RPM.png"
mv "mayday.png" "Mayday.png"
mv "megaman.png" "Mega Man  The Power Battle -mvS1, USA 951006-.png"
mv "mtwins.png" "Mega Twins -World 900619-.png"
mv "mercsu.png" "Mercs -World 900302-.png"
mv "mimonkey.png" "Mighty Monkey.png"
mv "minefld.png" "Minefield.png"
mv "mrviking.png" "Mister Viking.png"
mv "mooncrst.png" "Moon Cresta.png"
mv "mpatrol.png" "Moon Patrol.png"
mv "moonwar.png" "Moonwar.png"
mv "motos.png" "Motos.png"
mv "mrdo.png" "Mr. Do Fixed.png"
mv "mrdo.png" "Mr. Do Nightmare.png"
mv "mrdo.png" "Mr. Do.png"
mv "mrtnt.png" "Mr. TNT.png"
mv "mspacman.png" "Ms. Pacman.png"
mv "mbombrd2play.png" "Muscle Bomber Duo Ultimate Team Battle (World 931206).png"
mv "myhero.png" "My Hero.png"
mv "nemo.png" "Nemo -World 901130-.png"
mv "nrallyx.png" "New Rally-X.png"
mv "ninjakun.png" "Ninjakun.png"
mv "omega.png" "Omega.png"
mv "orbitron.png" "Orbitron.png"
mv "pacnpal.png" "Pamval.png"
mv "pacman.png" "Pac-Man (Midway).png"
mv "pacnchmp.png" "Pac-Man 26 Chomp Chomp.png"
mv "pacman.png" "Pacman Club.png"
mv "pacman.png" "Pacman Plus.png"
mv "pacmania.png" "Pacmanic Miner.png"
mv "pang3.png" "Pang! 3 -Euro 950601-.png"
mv "pengo.png" "Pengo.png"
mv "pestplce.png" "Pest Place.png"
mv "phoenix.png" "Phoenix.png"
mv "pickin.png" "Pickin'.png"
mv "higemaru.png" "Pirate Ship Higemaru.png"
mv "pisces.png" "Pisces.png"
mv "pitfall2.png" "Pitfall II (unencypted, cheat).png"
mv "pitfall2.png" "Pitfall II.png"
mv "playball.png" "Playball.png"
mv "pleiads.png" "Pleiads (Centuri).png"
mv "pleiads.png" "Pleiads (Tehkan).png"
mv "pleiads.png" "Pleiads.png"
mv "pnickj.png" "Pnickies -Japan 940608-.png"
mv "polyplay.png" "PolyPlay 2.png"
mv "polyplay.png" "PolyPlay 2c.png"
mv "polyplay.png" "PolyPlay.png"
mv "pong.png" "Pong.png"
mv "ponpoko.png" "Ponpoko.png"
mv "pooyan.png" "Pooyan.png"
mv "popeye.png" "Popeye.png"
mv "powerdrv2play.png" "Power Drive.png"
mv "puckman.png" "Puck Man (Japan set 1).png"
mv "qbert.png" "QBert.png"
mv "qad.png" "Quiz Dragons  Capcom Quiz Game -USA 920701-.png"
mv "radarsmv.png" "Radar Scope.png"
mv "raflesia.png" "Rafflesia.png"
mv "rallyx.png" "Rally-X.png"
mv "rampage2.png" "Rampage.png"
mv "regulus.png" "Regulus.png"
mv "rescue.png" "Rescue.png"
mv "rpatrol.png" "River Patrol.png"
mv "robby.png" "Robby Roto.png"
mv "robotron.png" "Robotron 2084.png"
mv "rushatck.png" "Rush'n Attack (US).png"
mv "rygar.png" "Rygar.png"
mv "sarge.png" "Sarge.png"
mv "shollow.png" "Satans Hollow.png"
mv "slammastu.png" "Saturday Night Slam Masters (World 930713).png"
mv "scramble.png" "Scramble.png"
mv "seawolf.png" "Sea Wolf.png"
mv "seawolf2.png" "Seawolf II.png"
mv "sectionz.png" "SectionZ.png"
mv "seganinj.png" "Sega Ninja.png"
mv "shtrider.png" "Shot Rider.png"
mv "shuffle.png" "Shuffleboard.png"
mv "shuttlei.png" "Shuttle Invader.png"
mv "sidearms.png" "Side Arms - Hyper Dyne (World, 861129).png"
mv "silkworm.png" "Silkworm.png"
mv "silvland.png" "Silver Land.png"
mv "sinistar.png" "Sinistar.png"
mv "skyskipr.png" "Sky Skipper.png"
mv "snapjack.png" "Snap Jack.png"
mv "koroleva.png" "Snezhnaja Koroleva.png"
mv "solarfox.png" "Solar Fox.png"
mv "solomonj.png" "Solomon no Kagi (Japan).png"
mv "solomon.png" "Solomon's Key.png"
mv "sos.png" "SOS.png"
mv "schaser.png" "Space Chaser.png"
mv "spcenctr.png" "Space Encounters.png"
mv "invadpt2.png" "Space Invaders II (Midway, cocktail).png"
mv "invadpt2.png" "Space Invaders Part II.png"
mv "invaders.png" "Space Invaders.png"
mv "spacezap.png" "Space Zap.png"
mv "spatter.png" "Spatter.png"
mv "spdcoin.png" "Speed Coin.png"
mv "spelunk2.png" "Spelunker II - 23 no Kagi.png"
mv "spelunkr.png" "Spelunker.png"
mv "splat.png" "Splat.png"
mv "sprint1.png" "Sprint 1.png"
mv "sprint2.png" "Sprint 2.png"
mv "spyhunt.png" "Spy Hunter.png"
mv "squash.png" "Squash.png"
mv "stargrds.png" "Star Guards.png"
mv "starjack.png" "Star Jacker.png"
mv "stargate.png" "Stargate.png"
mv "stratgyx.png" "Strategy X.png"
mv "sf.png" "Street Fighter (US, set 1).png"
mv "sf2.png" "Street Fighter II  The World Warrior -World 910522-.png"
mv "sf2ce.png" "Street Fighter II'  Champion Edition -World 920513-.png"
mv "sf2hf.png" "Street Fighter II'  Hyper Fighting -World 921209-.png"
mv "sfza.png" "Street Fighter Zero -mvS Changer, Japan 951020-.png"
mv "strider.png" "Strider -USA, B-Board 89624B-2-.png"
mv "sbagman.png" "Super Bagman.png"
mv "sbrkout.png" "Super Breakout.png"
mv "scobra.png" "Super Cobra.png"
mv "suprglob.png" "Super Glob.png"
mv "superpac.png" "Super Pacman.png"
mv "szaxxon.png" "Super Zaxxon.png"
mv "swat.png" "Swat.png"
mv "tapper.png" "Tapper.png"
mv "tazmania.png" "Tazz-Mania.png"
mv "teddybb.png" "TeddyBoy Blues.png"
mv "tetris.png" "Tetris (cocktail set 1).png"
mv "tetris.png" "Tetris.png"
mv "theend.png" "The End (bkg).png"
mv "theend.png" "The End.png"
mv "kodb.png" "The King of Dragons -World 910805-.png"
mv "punisher.png" "The Punisher (World 930422).png"
mv "srumbler.png" "The Speed Rumbler (set 1).png"
mv "3wonders.png" "Three Wonders -World 910520-.png"
mv "tigeroad.png" "Tiger Road.png"
mv "timber.png" "Timber.png"
mv "tp84.png" "Time Pilot '84 (Set 1).png"
mv "tp84.png" "Time Pilot '84 (Set 2).png"
mv "tp84.png" "Time Pilot '84 (Set 3).png"
mv "tp84.png" "Time Pilot.png"
mv "travrusa.png" "Traverse USA - Zippy Race.png"
mv "trojan.png" "Trojan (Romstar).png"
mv "tron.png" "Tron.png"
mv "turbotag.png" "Turbo Tag.png"
mv "turtles.png" "Turtles.png"
mv "twotiger.png" "Two Tigers.png"
mv "unsquad.png" "U.N. Squadron -USA-.png"
mv "ultratnk.png" "Ultra Tank.png"
mv "uniwars.png" "UniWar S.png"
mv "upndown.png" "Up'n Down.png"
mv "vanvan.png" "Van-Van Car.png"
mv "varth.png" "Varth  Operation Thunderstorm -World 920714-.png"
mv "victory.png" "Victory.png"
mv "vindctr2.png" "Vindicators Part II (rev 3).png"
mv "vortex.png" "Vortex.png"
mv "vulgus.png" "Vulgus.png"
mv "wacko.png" "Wacko.png"
mv "warofbug.png" "War of the Bugs.png"
mv "wofu.png" "Warriors of Fate (World 921031).png"
mv "wmatch.png" "Water Match.png"
mv "willow.png" "Willow -World-.png"
mv "wow.png" "Wizard of Wor - Speech.png"
mv "wow.png" "Wizard of Wor.png"
mv "wboy.png" "Wonder Boy.png"
mv "woodpeck.png" "Woodpecker.png"
mv "xevious.png" "Xevious.png"
mv "youjyudn.png" "Youjyuden.png"
mv "zaxxon.png" "zaxxon.png"
mv "zigzag.png" "Zig Zag.png"
