#!/bin/bash
cp 10yard85*.* /Users/al/Documents/Alu/alu
cp 3dTicTacToe*.* /Users/al/Documents/Alu/alu
cp 64street*.* /Users/al/Documents/Alu/alu
cp 8-Eyes-U-_edited*.* /Users/al/Documents/Alu/alu
cp Adventure*.* /Users/al/Documents/Alu/alu
cp AdventureII*.* /Users/al/Documents/Alu/alu
cp AirCavalry*.* /Users/al/Documents/Alu/alu
cp AirSeaBattle*.* /Users/al/Documents/Alu/alu
cp Al_Unser_Jr_Turbo_Racing*.* /Users/al/Documents/Alu/alu
cp Aladdin*.* /Users/al/Documents/Alu/alu
cp AlphabetZoo*.* /Users/al/Documents/Alu/alu
cp AntarcticAdventure*.* /Users/al/Documents/Alu/alu
cp Apocalypse2*.* /Users/al/Documents/Alu/alu
cp Aquattack*.* /Users/al/Documents/Alu/alu
cp Aquaventure*.* /Users/al/Documents/Alu/alu
cp ArtilleryDuel*.* /Users/al/Documents/Alu/alu
cp Asteroids*.* /Users/al/Documents/Alu/alu
cp Atarivideocube*.* /Users/al/Documents/Alu/alu
cp BBS_ENG_forPiko_final*.* /Users/al/Documents/Alu/alu
cp Backgammon*.* /Users/al/Documents/Alu/alu
cp Bad-Street-Brawler-USA_edit*.* /Users/al/Documents/Alu/alu
cp Basketball*.* /Users/al/Documents/Alu/alu
cp Basmath*.* /Users/al/Documents/Alu/alu
cp Battlenet*.* /Users/al/Documents/Alu/alu
cp Beamrider*.* /Users/al/Documents/Alu/alu
cp Beastball*.* /Users/al/Documents/Alu/alu
cp Blackjack*.* /Users/al/Documents/Alu/alu
cp BlackjackPoker*.* /Users/al/Documents/Alu/alu
cp BlockadeRunner*.* /Users/al/Documents/Alu/alu
cp Bowling*.* /Users/al/Documents/Alu/alu
cp Boxing*.* /Users/al/Documents/Alu/alu
cp BrainStrainers*.* /Users/al/Documents/Alu/alu
cp Braingms*.* /Users/al/Documents/Alu/alu
cp Breakout*.* /Users/al/Documents/Alu/alu
cp Bridge*.* /Users/al/Documents/Alu/alu
cp BumpAndJump*.* /Users/al/Documents/Alu/alu
cp BumpNJump*.* /Users/al/Documents/Alu/alu
cp Burgertime*.* /Users/al/Documents/Alu/alu
cp CONSOLE*.* /Users/al/Documents/Alu/alu
cp CanyonBomber*.* /Users/al/Documents/Alu/alu
cp CarrierAces_v2*.* /Users/al/Documents/Alu/alu
cp Casino*.* /Users/al/Documents/Alu/alu
cp Centipede*.* /Users/al/Documents/Alu/alu
cp ChampionWorldSoccer*.* /Users/al/Documents/Alu/alu
cp ChampionshipSoccer*.* /Users/al/Documents/Alu/alu
cp Checkers*.* /Users/al/Documents/Alu/alu
cp Choplifter*.* /Users/al/Documents/Alu/alu
cp ChopperCommand*.* /Users/al/Documents/Alu/alu
cp CircusAtari*.* /Users/al/Documents/Alu/alu
cp Codebrk*.* /Users/al/Documents/Alu/alu
cp Combat*.* /Users/al/Documents/Alu/alu
cp CommunityStreamingVisitor*.* /Users/al/Documents/Alu/alu
cp Concentr*.* /Users/al/Documents/Alu/alu
cp CongosCaper*.* /Users/al/Documents/Alu/alu
cp CosmicAvenger*.* /Users/al/Documents/Alu/alu
cp CosmicCommuter*.* /Users/al/Documents/Alu/alu
cp Crackpots*.* /Users/al/Documents/Alu/alu
cp CrystalCastles*.* /Users/al/Documents/Alu/alu
cp Dash-Galaxy-in-the-Alien-Asylum-USA_edit*.* /Users/al/Documents/Alu/alu
cp Decathlon*.* /Users/al/Documents/Alu/alu
cp Demon Attack*.* /Users/al/Documents/Alu/alu
cp DemonAttack*.* /Users/al/Documents/Alu/alu
cp DemonsToDiamonds*.* /Users/al/Documents/Alu/alu
cp DesertFalcon*.* /Users/al/Documents/Alu/alu
cp DodgeEm*.* /Users/al/Documents/Alu/alu
cp Dolphin*.* /Users/al/Documents/Alu/alu
cp DonaldDuck*.* /Users/al/Documents/Alu/alu
cp DoubleDunk*.* /Users/al/Documents/Alu/alu
cp DragonFire*.* /Users/al/Documents/Alu/alu
cp Dragonfire*.* /Users/al/Documents/Alu/alu
cp Dragster*.* /Users/al/Documents/Alu/alu
cp Elf_World_PIKO*.* /Users/al/Documents/Alu/alu
cp EliminatorBoatDuel*.* /Users/al/Documents/Alu/alu
cp Enduro*.* /Users/al/Documents/Alu/alu
cp Epic*.* /Users/al/Documents/Alu/alu
cp Evolution*.* /Users/al/Documents/Alu/alu
cp ExplodingFist*.* /Users/al/Documents/Alu/alu
cp Facemaker*.* /Users/al/Documents/Alu/alu
cp Fatalrun*.* /Users/al/Documents/Alu/alu
cp Fathom*.* /Users/al/Documents/Alu/alu
cp FishingDerby*.* /Users/al/Documents/Alu/alu
cp FlagCapture*.* /Users/al/Documents/Alu/alu
cp FlipperSlipper*.* /Users/al/Documents/Alu/alu
cp Football*.* /Users/al/Documents/Alu/alu
cp FortuneBuilder*.* /Users/al/Documents/Alu/alu
cp FranticFreddy*.* /Users/al/Documents/Alu/alu
cp Frenzy*.* /Users/al/Documents/Alu/alu
cp FrogPond*.* /Users/al/Documents/Alu/alu
cp GOG*.* /Users/al/Documents/Alu/alu
cp Gadget_Twins*.* /Users/al/Documents/Alu/alu
cp Gargoyles*.* /Users/al/Documents/Alu/alu
cp GatewayToApshai*.* /Users/al/Documents/Alu/alu
cp Golf*.* /Users/al/Documents/Alu/alu
cp GrandPrix*.* /Users/al/Documents/Alu/alu
cp Gravitar*.* /Users/al/Documents/Alu/alu
cp GustBuster*.* /Users/al/Documents/Alu/alu
cp Hangman*.* /Users/al/Documents/Alu/alu
cp HauntedHouse*.* /Users/al/Documents/Alu/alu
cp Hero*.* /Users/al/Documents/Alu/alu
cp HomeRun*.* /Users/al/Documents/Alu/alu
cp Home_Run_Nighter_90_The_Pennant_League*.* /Users/al/Documents/Alu/alu
cp Home_Run_Nighter_90_The_Pennant_League*.* /Users/al/Documents/Alu/alu
cp Hostages*.* /Users/al/Documents/Alu/alu
cp Hostages*.* /Users/al/Documents/Alu/alu
cp HumanCannonball*.* /Users/al/Documents/Alu/alu
cp Humans_the*.* /Users/al/Documents/Alu/alu
cp IceHockey*.* /Users/al/Documents/Alu/alu
cp Indy500*.* /Users/al/Documents/Alu/alu
cp Jaleco_Rally_Big_Run_The_Supreme_4WD_Challenge*.* /Users/al/Documents/Alu/alu
cp JoeMac*.* /Users/al/Documents/Alu/alu
cp Joe_Mac_2_Lost_in_the_Tropics*.* /Users/al/Documents/Alu/alu
cp JudgeDredd*.* /Users/al/Documents/Alu/alu
cp JumpmanJunior*.* /Users/al/Documents/Alu/alu
cp JungleBook*.* /Users/al/Documents/Alu/alu
cp JungleHunt*.* /Users/al/Documents/Alu/alu
cp Kabobber*.* /Users/al/Documents/Alu/alu
cp KingofKings*.* /Users/al/Documents/Alu/alu
cp KingofKings*.* /Users/al/Documents/Alu/alu
cp LaserBlast*.* /Users/al/Documents/Alu/alu
cp LionKing*.* /Users/al/Documents/Alu/alu
cp Little-Lancelot-The-Europe*.* /Users/al/Documents/Alu/alu
cp Little-Lancelot-The-Europe*.* /Users/al/Documents/Alu/alu
cp Little_Magic*.* /Users/al/Documents/Alu/alu
cp LockNChase*.* /Users/al/Documents/Alu/alu
cp MAGIC_GIRL_23_Oct_2018*.* /Users/al/Documents/Alu/alu
cp MGR*.* /Users/al/Documents/Alu/alu
cp MazeCraze*.* /Users/al/Documents/Alu/alu
cp Megamania*.* /Users/al/Documents/Alu/alu
cp MermaidsofAtlantis*.* /Users/al/Documents/Alu/alu
cp MermaidsofAtlantis*.* /Users/al/Documents/Alu/alu
cp MetalMech*.* /Users/al/Documents/Alu/alu
cp MetalMech*.* /Users/al/Documents/Alu/alu
cp Millipede*.* /Users/al/Documents/Alu/alu
cp Miner2049er*.* /Users/al/Documents/Alu/alu
cp MiniatureGolf*.* /Users/al/Documents/Alu/alu
cp MissileCommand*.* /Users/al/Documents/Alu/alu
cp MontezumasRevenge*.* /Users/al/Documents/Alu/alu
cp MoonSweeper*.* /Users/al/Documents/Alu/alu
cp Moonsweeper*.* /Users/al/Documents/Alu/alu
cp MotocrossRacer*.* /Users/al/Documents/Alu/alu
cp Motor-City-Patrol-U_edit*.* /Users/al/Documents/Alu/alu
cp Motor-City-Patrol-U_edit*.* /Users/al/Documents/Alu/alu
cp Motorodeo*.* /Users/al/Documents/Alu/alu
cp MountainBikeRally*.* /Users/al/Documents/Alu/alu
cp MountainKing*.* /Users/al/Documents/Alu/alu
cp MsSpaceFury*.* /Users/al/Documents/Alu/alu
cp Mutant-Virus-The-Crisis_edit*.* /Users/al/Documents/Alu/alu
cp Mutant-Virus-The-Crisis_edit*.* /Users/al/Documents/Alu/alu
cp NightDriver*.* /Users/al/Documents/Alu/alu
cp Nightshade-Part-1-The-Claws-of-Sutekh-USA_edit*.* /Users/al/Documents/Alu/alu
cp Nightshade-Part-1-The-Claws-of-Sutekh-USA_edit*.* /Users/al/Documents/Alu/alu
cp NovaBlast*.* /Users/al/Documents/Alu/alu
cp OffTheWall*.* /Users/al/Documents/Alu/alu
cp OilIsWell*.* /Users/al/Documents/Alu/alu
cp Oink*.* /Users/al/Documents/Alu/alu
cp OmegaRace*.* /Users/al/Documents/Alu/alu
cp Origin*.* /Users/al/Documents/Alu/alu
cp Outlaw*.* /Users/al/Documents/Alu/alu
cp Pepper2*.* /Users/al/Documents/Alu/alu
cp Pinkie*.* /Users/al/Documents/Alu/alu
cp Pitfall*.* /Users/al/Documents/Alu/alu
cp Pitfall2*.* /Users/al/Documents/Alu/alu
cp PlaqueAttack*.* /Users/al/Documents/Alu/alu
cp Power-Punch-II-USA_edit*.* /Users/al/Documents/Alu/alu
cp Power-Punch-II-USA_edit*.* /Users/al/Documents/Alu/alu
cp Powerpiggs*.* /Users/al/Documents/Alu/alu
cp PressureCooker*.* /Users/al/Documents/Alu/alu
cp PrivateEye*.* /Users/al/Documents/Alu/alu
cp Pyramids_of_Ra_FINAL*.* /Users/al/Documents/Alu/alu
cp Pyramids_of_Ra_FINAL*.* /Users/al/Documents/Alu/alu
cp Quadrun*.* /Users/al/Documents/Alu/alu
cp QuestForQuintanaRoo*.* /Users/al/Documents/Alu/alu
cp RadarLock*.* /Users/al/Documents/Alu/alu
cp RadicalRex*.* /Users/al/Documents/Alu/alu
cp RealSportsBaseball*.* /Users/al/Documents/Alu/alu
cp RealSportsBasketball*.* /Users/al/Documents/Alu/alu
cp RealSportsSoccer*.* /Users/al/Documents/Alu/alu
cp RealSportsVolleyball*.* /Users/al/Documents/Alu/alu
cp ReturnToHauntedHouse*.* /Users/al/Documents/Alu/alu
cp RiverRaid*.* /Users/al/Documents/Alu/alu
cp RiverRaidII*.* /Users/al/Documents/Alu/alu
cp RobotTank*.* /Users/al/Documents/Alu/alu
cp Rolloverture*.* /Users/al/Documents/Alu/alu
cp Rsboxing*.* /Users/al/Documents/Alu/alu
cp Rsfootb*.* /Users/al/Documents/Alu/alu
cp Rstennis*.* /Users/al/Documents/Alu/alu
cp SRD*.* /Users/al/Documents/Alu/alu
cp Saboteur*.* /Users/al/Documents/Alu/alu
cp SammyLightfoot*.* /Users/al/Documents/Alu/alu
cp SaveMary*.* /Users/al/Documents/Alu/alu
cp Seaquest*.* /Users/al/Documents/Alu/alu
cp SecretQuest*.* /Users/al/Documents/Alu/alu
cp Sentinel*.* /Users/al/Documents/Alu/alu
cp SidePocket*.* /Users/al/Documents/Alu/alu
cp SirLancelot*.* /Users/al/Documents/Alu/alu
cp Skiing*.* /Users/al/Documents/Alu/alu
cp Skuljagger*.* /Users/al/Documents/Alu/alu
cp SkyDiver*.* /Users/al/Documents/Alu/alu
cp SkyJinks*.* /Users/al/Documents/Alu/alu
cp Slither*.* /Users/al/Documents/Alu/alu
cp SlotMachine*.* /Users/al/Documents/Alu/alu
cp SlotRacers*.* /Users/al/Documents/Alu/alu
cp Slurpy*.* /Users/al/Documents/Alu/alu
cp Soccer_League_Winner_Cup*.* /Users/al/Documents/Alu/alu
cp Soccer_League_Winner_Cup*.* /Users/al/Documents/Alu/alu
cp SpaceFury*.* /Users/al/Documents/Alu/alu
cp SpacePanic*.* /Users/al/Documents/Alu/alu
cp SpaceShuttle*.* /Users/al/Documents/Alu/alu
cp SpaceWar*.* /Users/al/Documents/Alu/alu
cp Spelunker*.* /Users/al/Documents/Alu/alu
cp SpiderFighter*.* /Users/al/Documents/Alu/alu
cp SpiritualWarfare*.* /Users/al/Documents/Alu/alu
cp SprintMaster*.* /Users/al/Documents/Alu/alu
cp SquirrelKing*.* /Users/al/Documents/Alu/alu
cp SquishemSam*.* /Users/al/Documents/Alu/alu
cp Stampede*.* /Users/al/Documents/Alu/alu
cp Stanley*.* /Users/al/Documents/Alu/alu
cp Stanley*.* /Users/al/Documents/Alu/alu
cp StarShip*.* /Users/al/Documents/Alu/alu
cp Steeplechase*.* /Users/al/Documents/Alu/alu
cp StellarTrack*.* /Users/al/Documents/Alu/alu
cp StreetRacer*.* /Users/al/Documents/Alu/alu
cp SubmarineCommander*.* /Users/al/Documents/Alu/alu
cp SundayFunday*.* /Users/al/Documents/Alu/alu
cp SundayFunday*.* /Users/al/Documents/Alu/alu
cp SuperActionBaseball*.* /Users/al/Documents/Alu/alu
cp SuperActionBoxing*.* /Users/al/Documents/Alu/alu
cp SuperActionFootball*.* /Users/al/Documents/Alu/alu
cp SuperActionSoccer*.* /Users/al/Documents/Alu/alu
cp SuperBaseball*.* /Users/al/Documents/Alu/alu
cp SuperBreakout*.* /Users/al/Documents/Alu/alu
cp SuperCrossForce*.* /Users/al/Documents/Alu/alu
cp SuperFootball*.* /Users/al/Documents/Alu/alu
cp SuperStarWars*.* /Users/al/Documents/Alu/alu
cp SuperStarWars2*.* /Users/al/Documents/Alu/alu
cp SuperStarWars3*.* /Users/al/Documents/Alu/alu
cp Super_Birdie_Rush*.* /Users/al/Documents/Alu/alu
cp Surround*.* /Users/al/Documents/Alu/alu
cp SwitchbladeGenesis_Final*.* /Users/al/Documents/Alu/alu
cp SwordQuestEarthworld*.* /Users/al/Documents/Alu/alu
cp SwordQuestFireworld*.* /Users/al/Documents/Alu/alu
cp SwordQuestWaterworld*.* /Users/al/Documents/Alu/alu
cp Sword_of_Sodan_Piko_no_sega*.* /Users/al/Documents/Alu/alu
cp Target-Renegade-U-_edited*.* /Users/al/Documents/Alu/alu
cp Target-Renegade-U-_edited*.* /Users/al/Documents/Alu/alu
cp TellyTurtle*.* /Users/al/Documents/Alu/alu
cp Tempest*.* /Users/al/Documents/Alu/alu
cp Tennis*.* /Users/al/Documents/Alu/alu
cp Tetris*.* /Users/al/Documents/Alu/alu
cp Tetris*.* /Users/al/Documents/Alu/alu
cp Tg2_conn2*.* /Users/al/Documents/Alu/alu
cp TheDamBuster*.* /Users/al/Documents/Alu/alu
cp TheHeist*.* /Users/al/Documents/Alu/alu
cp Threshold*.* /Users/al/Documents/Alu/alu
cp Thunderbolt_II_PIKO_v5*.* /Users/al/Documents/Alu/alu
cp Thunderbolt_final*.* /Users/al/Documents/Alu/alu
cp Thunderbolt_final*.* /Users/al/Documents/Alu/alu
cp Thwocker*.* /Users/al/Documents/Alu/alu
cp TinHead*.* /Users/al/Documents/Alu/alu
cp TomarcTheBarbarian*.* /Users/al/Documents/Alu/alu
cp TopGear2*.* /Users/al/Documents/Alu/alu
cp Topracer1*.* /Users/al/Documents/Alu/alu
cp TournamentTennis*.* /Users/al/Documents/Alu/alu
cp Treasure-Master-USA_edit*.* /Users/al/Documents/Alu/alu
cp Treasure-Master-USA_edit*.* /Users/al/Documents/Alu/alu
cp UPlay*.* /Users/al/Documents/Alu/alu
cp Venture*.* /Users/al/Documents/Alu/alu
cp Victory*.* /Users/al/Documents/Alu/alu
cp VideoCheckers*.* /Users/al/Documents/Alu/alu
cp VideoChess*.* /Users/al/Documents/Alu/alu
cp VideoOlympics*.* /Users/al/Documents/Alu/alu
cp VideoPinball*.* /Users/al/Documents/Alu/alu
cp WarRoom*.* /Users/al/Documents/Alu/alu
cp Warlords*.* /Users/al/Documents/Alu/alu
cp WarpSpeedv3*.* /Users/al/Documents/Alu/alu
cp Water_Margin_Final*.* /Users/al/Documents/Alu/alu
cp WingWar*.* /Users/al/Documents/Alu/alu
cp Wizard*.* /Users/al/Documents/Alu/alu
cp WorldTrophySoccer*.* /Users/al/Documents/Alu/alu
cp Yang_Warrior_Family_10_Oct_2016*.* /Users/al/Documents/Alu/alu
cp YarsReturn*.* /Users/al/Documents/Alu/alu
cp YarsRevenge*.* /Users/al/Documents/Alu/alu
cp Zaombies*.* /Users/al/Documents/Alu/alu
cp Zaxxon*.* /Users/al/Documents/Alu/alu
cp ZeroTolerance*.* /Users/al/Documents/Alu/alu
cp abaseb*.* /Users/al/Documents/Alu/alu
cp actfancr*.* /Users/al/Documents/Alu/alu
cp all-games*.* /Users/al/Documents/Alu/alu
cp all-games*.* /Users/al/Documents/Alu/alu
cp alugames*.* /Users/al/Documents/Alu/alu
cp argus*.* /Users/al/Documents/Alu/alu
cp astdelux*.* /Users/al/Documents/Alu/alu
cp asteroid*.* /Users/al/Documents/Alu/alu
cp astyanax*.* /Users/al/Documents/Alu/alu
cp atarifb*.* /Users/al/Documents/Alu/alu
cp avalnche*.* /Users/al/Documents/Alu/alu
cp avspirit*.* /Users/al/Documents/Alu/alu
cp baddudes*.* /Users/al/Documents/Alu/alu
cp battroad*.* /Users/al/Documents/Alu/alu
cp bbbxing*.* /Users/al/Documents/Alu/alu
cp bchopper*.* /Users/al/Documents/Alu/alu
cp bigrun*.* /Users/al/Documents/Alu/alu
cp birdtry*.* /Users/al/Documents/Alu/alu
cp bldwolf*.* /Users/al/Documents/Alu/alu
cp boogwing*.* /Users/al/Documents/Alu/alu
cp boomrang*.* /Users/al/Documents/Alu/alu
cp brkthru*.* /Users/al/Documents/Alu/alu
cp brubber*.* /Users/al/Documents/Alu/alu
cp bsktball*.* /Users/al/Documents/Alu/alu
cp btime*.* /Users/al/Documents/Alu/alu
cp butasan*.* /Users/al/Documents/Alu/alu
cp bwidow*.* /Users/al/Documents/Alu/alu
cp bwings*.* /Users/al/Documents/Alu/alu
cp byog_loc*.* /Users/al/Documents/Alu/alu
cp byog_special_loc*.* /Users/al/Documents/Alu/alu
cp cadanglr*.* /Users/al/Documents/Alu/alu
cp canyon*.* /Users/al/Documents/Alu/alu
cp castfant*.* /Users/al/Documents/Alu/alu
cp cbuster*.* /Users/al/Documents/Alu/alu
cp ccastles*.* /Users/al/Documents/Alu/alu
cp centiped*.* /Users/al/Documents/Alu/alu
cp cfghtice*.* /Users/al/Documents/Alu/alu
cp cgraplop*.* /Users/al/Documents/Alu/alu
cp chainrec*.* /Users/al/Documents/Alu/alu
cp chameleo*.* /Users/al/Documents/Alu/alu
cp chimerab*.* /Users/al/Documents/Alu/alu
cp chinatwn*.* /Users/al/Documents/Alu/alu
cp cischeat*.* /Users/al/Documents/Alu/alu
cp citycon*.* /Users/al/Documents/Alu/alu
cp clapapa*.* /Users/al/Documents/Alu/alu
cp cluckypo*.* /Users/al/Documents/Alu/alu
cp cmissnx*.* /Users/al/Documents/Alu/alu
cp cnightst*.* /Users/al/Documents/Alu/alu
cp cninja*.* /Users/al/Documents/Alu/alu
cp comingsoon*.* /Users/al/Documents/Alu/alu
cp compgolf*.* /Users/al/Documents/Alu/alu
cp coozumou*.* /Users/al/Documents/Alu/alu
cp cppicf*.* /Users/al/Documents/Alu/alu
cp cprobowl*.* /Users/al/Documents/Alu/alu
cp cprogolf*.* /Users/al/Documents/Alu/alu
cp cptennis*.* /Users/al/Documents/Alu/alu
cp cscrtry*.* /Users/al/Documents/Alu/alu
cp csilver*.* /Users/al/Documents/Alu/alu
cp cterrani*.* /Users/al/Documents/Alu/alu
cp ctisland*.* /Users/al/Documents/Alu/alu
cp cybattlr*.* /Users/al/Documents/Alu/alu
cp darkseal*.* /Users/al/Documents/Alu/alu
cp darwin*.* /Users/al/Documents/Alu/alu
cp dassault*.* /Users/al/Documents/Alu/alu
cp dbreed*.* /Users/al/Documents/Alu/alu
cp dday*.* /Users/al/Documents/Alu/alu
cp ddream95*.* /Users/al/Documents/Alu/alu
cp desertwr*.* /Users/al/Documents/Alu/alu
cp destroyr*.* /Users/al/Documents/Alu/alu
cp disco*.* /Users/al/Documents/Alu/alu
cp dominos*.* /Users/al/Documents/Alu/alu
cp dorkeandymp*.* /Users/al/Documents/Alu/alu
cp dragngun*.* /Users/al/Documents/Alu/alu
cp dragon-view-modified*.* /Users/al/Documents/Alu/alu
cp dragrace*.* /Users/al/Documents/Alu/alu
cp drakkhen*.* /Users/al/Documents/Alu/alu
cp edf*.* /Users/al/Documents/Alu/alu
cp edrandy*.* /Users/al/Documents/Alu/alu
cp exerion*.* /Users/al/Documents/Alu/alu
cp exerizrb*.* /Users/al/Documents/Alu/alu
cp exprraid*.* /Users/al/Documents/Alu/alu
cp fcombat*.* /Users/al/Documents/Alu/alu
cp featured*.* /Users/al/Documents/Alu/alu
cp ffantasy*.* /Users/al/Documents/Alu/alu
cp fghthistu*.* /Users/al/Documents/Alu/alu
cp fif*.* /Users/al/Documents/Alu/alu
cp firetrk*.* /Users/al/Documents/Alu/alu
cp formatz*.* /Users/al/Documents/Alu/alu
cp fullthrottle*.* /Users/al/Documents/Alu/alu
cp gallop*.* /Users/al/Documents/Alu/alu
cp gondo*.* /Users/al/Documents/Alu/alu
cp gourmet*.* /Users/al/Documents/Alu/alu
cp gratia*.* /Users/al/Documents/Alu/alu
cp gravitar*.* /Users/al/Documents/Alu/alu
cp hachoo*.* /Users/al/Documents/Alu/alu
cp hbarrel*.* /Users/al/Documents/Alu/alu
cp hharry*.* /Users/al/Documents/Alu/alu
cp hvysmsh*.* /Users/al/Documents/Alu/alu
cp iganinju*.* /Users/al/Documents/Alu/alu
cp immortal*.* /Users/al/Documents/Alu/alu
cp ironcommando*.* /Users/al/Documents/Alu/alu
cp jimpower*.* /Users/al/Documents/Alu/alu
cp joemacr*.* /Users/al/Documents/Alu/alu
cp kamikcab*.* /Users/al/Documents/Alu/alu
cp karnovr*.* /Users/al/Documents/Alu/alu
cp kazan*.* /Users/al/Documents/Alu/alu
cp kchamp*.* /Users/al/Documents/Alu/alu
cp kengo*.* /Users/al/Documents/Alu/alu
cp kungfum*.* /Users/al/Documents/Alu/alu
cp lastmisn*.* /Users/al/Documents/Alu/alu
cp ldrun*.* /Users/al/Documents/Alu/alu
cp ldrun2*.* /Users/al/Documents/Alu/alu
cp ldrun3*.* /Users/al/Documents/Alu/alu
cp ldrun4*.* /Users/al/Documents/Alu/alu
cp legend_E_v3*.* /Users/al/Documents/Alu/alu
cp liberate*.* /Users/al/Documents/Alu/alu
cp liberatr*.* /Users/al/Documents/Alu/alu
cp llander*.* /Users/al/Documents/Alu/alu
cp lnc*.* /Users/al/Documents/Alu/alu
cp lockload*.* /Users/al/Documents/Alu/alu
cp loht*.* /Users/al/Documents/Alu/alu
cp lomakai*.* /Users/al/Documents/Alu/alu
cp lordofk*.* /Users/al/Documents/Alu/alu
cp magdrop*.* /Users/al/Documents/Alu/alu
cp magdrop2*.* /Users/al/Documents/Alu/alu
cp magdrop3*.* /Users/al/Documents/Alu/alu
cp majtitle*.* /Users/al/Documents/Alu/alu
cp makaiden*.* /Users/al/Documents/Alu/alu
cp meikyuh*.* /Users/al/Documents/Alu/alu
cp metlclsh*.* /Users/al/Documents/Alu/alu
cp mhavoc*.* /Users/al/Documents/Alu/alu
cp midres*.* /Users/al/Documents/Alu/alu
cp midresu*.* /Users/al/Documents/Alu/alu
cp milliped*.* /Users/al/Documents/Alu/alu
cp missile*.* /Users/al/Documents/Alu/alu
cp montecar*.* /Users/al/Documents/Alu/alu
cp mpatrol*.* /Users/al/Documents/Alu/alu
cp mrbloopy*.* /Users/al/Documents/Alu/alu
cp mspacman*.* /Users/al/Documents/Alu/alu
cp mutantf*.* /Users/al/Documents/Alu/alu
cp naughtyb*.* /Users/al/Documents/Alu/alu
cp nitrobal*.* /Users/al/Documents/Alu/alu
cp nob*.* /Users/al/Documents/Alu/alu
cp nslasher*.* /Users/al/Documents/Alu/alu
cp nslashers*.* /Users/al/Documents/Alu/alu
cp nspirit*.* /Users/al/Documents/Alu/alu
cp oscar*.* /Users/al/Documents/Alu/alu
cp p47*.* /Users/al/Documents/Alu/alu
cp p47aces*.* /Users/al/Documents/Alu/alu
cp p47j*.* /Users/al/Documents/Alu/alu
cp phantasm*.* /Users/al/Documents/Alu/alu
cp pinbo*.* /Users/al/Documents/Alu/alu
cp plusalph*.* /Users/al/Documents/Alu/alu
cp pong*.* /Users/al/Documents/Alu/alu
cp poolshrk*.* /Users/al/Documents/Alu/alu
cp popflame*.* /Users/al/Documents/Alu/alu
cp prosoccr*.* /Users/al/Documents/Alu/alu
cp psychic5*.* /Users/al/Documents/Alu/alu
cp pturn*.* /Users/al/Documents/Alu/alu
cp redbaron*.* /Users/al/Documents/Alu/alu
cp rodland*.* /Users/al/Documents/Alu/alu
cp rtype*.* /Users/al/Documents/Alu/alu
cp rtype2*.* /Users/al/Documents/Alu/alu
cp rtypeleo*.* /Users/al/Documents/Alu/alu
cp saturn*.* /Users/al/Documents/Alu/alu
cp sbrkout*.* /Users/al/Documents/Alu/alu
cp scudhamm*.* /Users/al/Documents/Alu/alu
cp sdtennis*.* /Users/al/Documents/Alu/alu
cp secretag*.* /Users/al/Documents/Alu/alu
cp shackled*.* /Users/al/Documents/Alu/alu
cp shootout*.* /Users/al/Documents/Alu/alu
cp sidepckt*.* /Users/al/Documents/Alu/alu
cp skydiver*.* /Users/al/Documents/Alu/alu
cp skyfox*.* /Users/al/Documents/Alu/alu
cp soccer*.* /Users/al/Documents/Alu/alu
cp soccerkid*.* /Users/al/Documents/Alu/alu
cp soldamj*.* /Users/al/Documents/Alu/alu
cp spacduel*.* /Users/al/Documents/Alu/alu
cp spelunkr*.* /Users/al/Documents/Alu/alu
cp spinmast*.* /Users/al/Documents/Alu/alu
cp spool3*.* /Users/al/Documents/Alu/alu
cp sprint1*.* /Users/al/Documents/Alu/alu
cp srdarwin*.* /Users/al/Documents/Alu/alu
cp stadhero*.* /Users/al/Documents/Alu/alu
cp stdragon*.* /Users/al/Documents/Alu/alu
cp strhoop*.* /Users/al/Documents/Alu/alu
cp stunt*.* /Users/al/Documents/Alu/alu
cp supbtime*.* /Users/al/Documents/Alu/alu
cp superbug*.* /Users/al/Documents/Alu/alu
cp tempest*.* /Users/al/Documents/Alu/alu
cp tetrisp*.* /Users/al/Documents/Alu/alu
cp tetrisp2*.* /Users/al/Documents/Alu/alu
cp topracer3000*.* /Users/al/Documents/Alu/alu
cp travrusa*.* /Users/al/Documents/Alu/alu
cp triothep*.* /Users/al/Documents/Alu/alu
cp troangel*.* /Users/al/Documents/Alu/alu
cp tron*.* /Users/al/Documents/Alu/alu
cp tryout*.* /Users/al/Documents/Alu/alu
cp tshingen*.* /Users/al/Documents/Alu/alu
cp tshingna*.* /Users/al/Documents/Alu/alu
cp tumblep*.* /Users/al/Documents/Alu/alu
cp universalboxart*.* /Users/al/Documents/Alu/alu
cp valtric*.* /Users/al/Documents/Alu/alu
cp warlords*.* /Users/al/Documents/Alu/alu
cp wizdfire*.* /Users/al/Documents/Alu/alu
cp wndrplnt*.* /Users/al/Documents/Alu/alu
cp xmultipl*.* /Users/al/Documents/Alu/alu
cp zaviga*.* /Users/al/Documents/Alu/alu
