#!/bin/bash
cp -n 10yard85.png /Users/al/Documents/Alu/alu
cp -n 3dTicTacToe.png /Users/al/Documents/Alu/alu
cp -n 64street.png /Users/al/Documents/Alu/alu
cp -n 8-Eyes-U-_edited.png /Users/al/Documents/Alu/alu
cp -n Adventure.png /Users/al/Documents/Alu/alu
cp -n AdventureII.png /Users/al/Documents/Alu/alu
cp -n AirCavalry.png /Users/al/Documents/Alu/alu
cp -n AirSeaBattle.png /Users/al/Documents/Alu/alu
cp -n Al_Unser_Jr_Turbo_Racing.png /Users/al/Documents/Alu/alu
cp -n Aladdin.png /Users/al/Documents/Alu/alu
cp -n AlphabetZoo.png /Users/al/Documents/Alu/alu
cp -n AntarcticAdventure.png /Users/al/Documents/Alu/alu
cp -n Apocalypse2.png /Users/al/Documents/Alu/alu
cp -n Aquattack.png /Users/al/Documents/Alu/alu
cp -n Aquaventure.png /Users/al/Documents/Alu/alu
cp -n ArtilleryDuel.png /Users/al/Documents/Alu/alu
cp -n Asteroids.png /Users/al/Documents/Alu/alu
cp -n Atarivideocube.png /Users/al/Documents/Alu/alu
cp -n BBS_ENG_forPiko_final.png /Users/al/Documents/Alu/alu
cp -n Backgammon.png /Users/al/Documents/Alu/alu
cp -n Bad-Street-Brawler-USA_edit.png /Users/al/Documents/Alu/alu
cp -n Basketball.png /Users/al/Documents/Alu/alu
cp -n Basmath.png /Users/al/Documents/Alu/alu
cp -n Battlenet.png /Users/al/Documents/Alu/alu
cp -n Beamrider.png /Users/al/Documents/Alu/alu
cp -n Beastball.png /Users/al/Documents/Alu/alu
cp -n Blackjack.png /Users/al/Documents/Alu/alu
cp -n BlackjackPoker.png /Users/al/Documents/Alu/alu
cp -n BlockadeRunner.png /Users/al/Documents/Alu/alu
cp -n Bowling.png /Users/al/Documents/Alu/alu
cp -n Boxing.png /Users/al/Documents/Alu/alu
cp -n BrainStrainers.png /Users/al/Documents/Alu/alu
cp -n Braingms.png /Users/al/Documents/Alu/alu
cp -n Breakout.png /Users/al/Documents/Alu/alu
cp -n Bridge.png /Users/al/Documents/Alu/alu
cp -n BumpAndJump.png /Users/al/Documents/Alu/alu
cp -n BumpNJump.png /Users/al/Documents/Alu/alu
cp -n Burgertime.png /Users/al/Documents/Alu/alu
cp -n CanyonBomber.png /Users/al/Documents/Alu/alu
cp -n CarrierAces_v2.png /Users/al/Documents/Alu/alu
cp -n Casino.png /Users/al/Documents/Alu/alu
cp -n Centipede.png /Users/al/Documents/Alu/alu
cp -n ChampionWorldSoccer.png /Users/al/Documents/Alu/alu
cp -n ChampionshipSoccer.png /Users/al/Documents/Alu/alu
cp -n Checkers.png /Users/al/Documents/Alu/alu
cp -n Choplifter.png /Users/al/Documents/Alu/alu
cp -n ChopperCommand.png /Users/al/Documents/Alu/alu
cp -n CircusAtari.png /Users/al/Documents/Alu/alu
cp -n Codebrk.png /Users/al/Documents/Alu/alu
cp -n Combat.png /Users/al/Documents/Alu/alu
cp -n CommunityStreamingVisitor.png /Users/al/Documents/Alu/alu
cp -n Concentr.png /Users/al/Documents/Alu/alu
cp -n CongosCaper.png /Users/al/Documents/Alu/alu
cp -n CosmicAvenger.png /Users/al/Documents/Alu/alu
cp -n CosmicCommuter.png /Users/al/Documents/Alu/alu
cp -n Crackpots.png /Users/al/Documents/Alu/alu
cp -n CrystalCastles.png /Users/al/Documents/Alu/alu
cp -n Dash-Galaxy-in-the-Alien-Asylum-USA_edit.png /Users/al/Documents/Alu/alu
cp -n Decathlon.png /Users/al/Documents/Alu/alu
cp -n Demon Attack.png /Users/al/Documents/Alu/alu
cp -n DemonAttack.png /Users/al/Documents/Alu/alu
cp -n DemonsToDiamonds.png /Users/al/Documents/Alu/alu
cp -n DesertFalcon.png /Users/al/Documents/Alu/alu
cp -n DodgeEm.png /Users/al/Documents/Alu/alu
cp -n Dolphin.png /Users/al/Documents/Alu/alu
cp -n DonaldDuck.png /Users/al/Documents/Alu/alu
cp -n DoubleDunk.png /Users/al/Documents/Alu/alu
cp -n DragonFire.png /Users/al/Documents/Alu/alu
cp -n Dragonfire.png /Users/al/Documents/Alu/alu
cp -n Dragster.png /Users/al/Documents/Alu/alu
cp -n Elf_World_PIKO.png /Users/al/Documents/Alu/alu
cp -n EliminatorBoatDuel.png /Users/al/Documents/Alu/alu
cp -n Enduro.png /Users/al/Documents/Alu/alu
cp -n Epic.png /Users/al/Documents/Alu/alu
cp -n Evolution.png /Users/al/Documents/Alu/alu
cp -n ExplodingFist.png /Users/al/Documents/Alu/alu
cp -n Facemaker.png /Users/al/Documents/Alu/alu
cp -n Fatalrun.png /Users/al/Documents/Alu/alu
cp -n Fathom.png /Users/al/Documents/Alu/alu
cp -n FishingDerby.png /Users/al/Documents/Alu/alu
cp -n FlagCapture.png /Users/al/Documents/Alu/alu
cp -n FlipperSlipper.png /Users/al/Documents/Alu/alu
cp -n Football.png /Users/al/Documents/Alu/alu
cp -n FortuneBuilder.png /Users/al/Documents/Alu/alu
cp -n FranticFreddy.png /Users/al/Documents/Alu/alu
cp -n Frenzy.png /Users/al/Documents/Alu/alu
cp -n FrogPond.png /Users/al/Documents/Alu/alu
cp -n GOG.png /Users/al/Documents/Alu/alu
cp -n Gadget_Twins.png /Users/al/Documents/Alu/alu
cp -n Gargoyles.png /Users/al/Documents/Alu/alu
cp -n GatewayToApshai.png /Users/al/Documents/Alu/alu
cp -n Golf.png /Users/al/Documents/Alu/alu
cp -n GrandPrix.png /Users/al/Documents/Alu/alu
cp -n Gravitar.png /Users/al/Documents/Alu/alu
cp -n GustBuster.png /Users/al/Documents/Alu/alu
cp -n Hangman.png /Users/al/Documents/Alu/alu
cp -n HauntedHouse.png /Users/al/Documents/Alu/alu
cp -n Hero.png /Users/al/Documents/Alu/alu
cp -n HomeRun.png /Users/al/Documents/Alu/alu
cp -n Home_Run_Nighter_90_The_Pennant_League.png /Users/al/Documents/Alu/alu
cp -n Home_Run_Nighter_90_The_Pennant_League.png /Users/al/Documents/Alu/alu
cp -n Hostages.png /Users/al/Documents/Alu/alu
cp -n Hostages.png /Users/al/Documents/Alu/alu
cp -n HumanCannonball.png /Users/al/Documents/Alu/alu
cp -n Humans_the.png /Users/al/Documents/Alu/alu
cp -n IceHockey.png /Users/al/Documents/Alu/alu
cp -n Indy500.png /Users/al/Documents/Alu/alu
cp -n Jaleco_Rally_Big_Run_The_Supreme_4WD_Challenge.png /Users/al/Documents/Alu/alu
cp -n JoeMac.png /Users/al/Documents/Alu/alu
cp -n Joe_Mac_2_Lost_in_the_Tropics.png /Users/al/Documents/Alu/alu
cp -n JudgeDredd.png /Users/al/Documents/Alu/alu
cp -n JumpmanJunior.png /Users/al/Documents/Alu/alu
cp -n JungleBook.png /Users/al/Documents/Alu/alu
cp -n JungleHunt.png /Users/al/Documents/Alu/alu
cp -n Kabobber.png /Users/al/Documents/Alu/alu
cp -n KingofKings.png /Users/al/Documents/Alu/alu
cp -n KingofKings.png /Users/al/Documents/Alu/alu
cp -n LaserBlast.png /Users/al/Documents/Alu/alu
cp -n LionKing.png /Users/al/Documents/Alu/alu
cp -n Little-Lancelot-The-Europe.png /Users/al/Documents/Alu/alu
cp -n Little-Lancelot-The-Europe.png /Users/al/Documents/Alu/alu
cp -n Little_Magic.png /Users/al/Documents/Alu/alu
cp -n LockNChase.png /Users/al/Documents/Alu/alu
cp -n MAGIC_GIRL_23_Oct_2018.png /Users/al/Documents/Alu/alu
cp -n MGR.png /Users/al/Documents/Alu/alu
cp -n MazeCraze.png /Users/al/Documents/Alu/alu
cp -n Megamania.png /Users/al/Documents/Alu/alu
cp -n MermaidsofAtlantis.png /Users/al/Documents/Alu/alu
cp -n MermaidsofAtlantis.png /Users/al/Documents/Alu/alu
cp -n MetalMech.png /Users/al/Documents/Alu/alu
cp -n MetalMech.png /Users/al/Documents/Alu/alu
cp -n Millipede.png /Users/al/Documents/Alu/alu
cp -n Miner2049er.png /Users/al/Documents/Alu/alu
cp -n MiniatureGolf.png /Users/al/Documents/Alu/alu
cp -n MissileCommand.png /Users/al/Documents/Alu/alu
cp -n MontezumasRevenge.png /Users/al/Documents/Alu/alu
cp -n MoonSweeper.png /Users/al/Documents/Alu/alu
cp -n Moonsweeper.png /Users/al/Documents/Alu/alu
cp -n MotocrossRacer.png /Users/al/Documents/Alu/alu
cp -n Motor-City-Patrol-U_edit.png /Users/al/Documents/Alu/alu
cp -n Motor-City-Patrol-U_edit.png /Users/al/Documents/Alu/alu
cp -n Motorodeo.png /Users/al/Documents/Alu/alu
cp -n MountainBikeRally.png /Users/al/Documents/Alu/alu
cp -n MountainKing.png /Users/al/Documents/Alu/alu
cp -n MsSpaceFury.png /Users/al/Documents/Alu/alu
cp -n Mutant-Virus-The-Crisis_edit.png /Users/al/Documents/Alu/alu
cp -n Mutant-Virus-The-Crisis_edit.png /Users/al/Documents/Alu/alu
cp -n NightDriver.png /Users/al/Documents/Alu/alu
cp -n Nightshade-Part-1-The-Claws-of-Sutekh-USA_edit.png /Users/al/Documents/Alu/alu
cp -n Nightshade-Part-1-The-Claws-of-Sutekh-USA_edit.png /Users/al/Documents/Alu/alu
cp -n NovaBlast.png /Users/al/Documents/Alu/alu
cp -n OffTheWall.png /Users/al/Documents/Alu/alu
cp -n OilIsWell.png /Users/al/Documents/Alu/alu
cp -n Oink.png /Users/al/Documents/Alu/alu
cp -n OmegaRace.png /Users/al/Documents/Alu/alu
cp -n Origin.png /Users/al/Documents/Alu/alu
cp -n Outlaw.png /Users/al/Documents/Alu/alu
cp -n Pepper2.png /Users/al/Documents/Alu/alu
cp -n Pinkie.png /Users/al/Documents/Alu/alu
cp -n Pitfall.png /Users/al/Documents/Alu/alu
cp -n Pitfall2.png /Users/al/Documents/Alu/alu
cp -n PlaqueAttack.png /Users/al/Documents/Alu/alu
cp -n Power-Punch-II-USA_edit.png /Users/al/Documents/Alu/alu
cp -n Power-Punch-II-USA_edit.png /Users/al/Documents/Alu/alu
cp -n Powerpiggs.png /Users/al/Documents/Alu/alu
cp -n PressureCooker.png /Users/al/Documents/Alu/alu
cp -n PrivateEye.png /Users/al/Documents/Alu/alu
cp -n Pyramids_of_Ra_FINAL.png /Users/al/Documents/Alu/alu
cp -n Pyramids_of_Ra_FINAL.png /Users/al/Documents/Alu/alu
cp -n Quadrun.png /Users/al/Documents/Alu/alu
cp -n QuestForQuintanaRoo.png /Users/al/Documents/Alu/alu
cp -n RadarLock.png /Users/al/Documents/Alu/alu
cp -n RadicalRex.png /Users/al/Documents/Alu/alu
cp -n RealSportsBaseball.png /Users/al/Documents/Alu/alu
cp -n RealSportsBasketball.png /Users/al/Documents/Alu/alu
cp -n RealSportsSoccer.png /Users/al/Documents/Alu/alu
cp -n RealSportsVolleyball.png /Users/al/Documents/Alu/alu
cp -n ReturnToHauntedHouse.png /Users/al/Documents/Alu/alu
cp -n RiverRaid.png /Users/al/Documents/Alu/alu
cp -n RiverRaidII.png /Users/al/Documents/Alu/alu
cp -n RobotTank.png /Users/al/Documents/Alu/alu
cp -n Rolloverture.png /Users/al/Documents/Alu/alu
cp -n Rsboxing.png /Users/al/Documents/Alu/alu
cp -n Rsfootb.png /Users/al/Documents/Alu/alu
cp -n Rstennis.png /Users/al/Documents/Alu/alu
cp -n SRD.png /Users/al/Documents/Alu/alu
cp -n Saboteur.png /Users/al/Documents/Alu/alu
cp -n SammyLightfoot.png /Users/al/Documents/Alu/alu
cp -n SaveMary.png /Users/al/Documents/Alu/alu
cp -n Seaquest.png /Users/al/Documents/Alu/alu
cp -n SecretQuest.png /Users/al/Documents/Alu/alu
cp -n Sentinel.png /Users/al/Documents/Alu/alu
cp -n SidePocket.png /Users/al/Documents/Alu/alu
cp -n SirLancelot.png /Users/al/Documents/Alu/alu
cp -n Skiing.png /Users/al/Documents/Alu/alu
cp -n Skuljagger.png /Users/al/Documents/Alu/alu
cp -n SkyDiver.png /Users/al/Documents/Alu/alu
cp -n SkyJinks.png /Users/al/Documents/Alu/alu
cp -n Slither.png /Users/al/Documents/Alu/alu
cp -n SlotMachine.png /Users/al/Documents/Alu/alu
cp -n SlotRacers.png /Users/al/Documents/Alu/alu
cp -n Slurpy.png /Users/al/Documents/Alu/alu
cp -n Soccer_League_Winner_Cup.png /Users/al/Documents/Alu/alu
cp -n Soccer_League_Winner_Cup.png /Users/al/Documents/Alu/alu
cp -n SpaceFury.png /Users/al/Documents/Alu/alu
cp -n SpacePanic.png /Users/al/Documents/Alu/alu
cp -n SpaceShuttle.png /Users/al/Documents/Alu/alu
cp -n SpaceWar.png /Users/al/Documents/Alu/alu
cp -n Spelunker.png /Users/al/Documents/Alu/alu
cp -n SpiderFighter.png /Users/al/Documents/Alu/alu
cp -n SpiritualWarfare.png /Users/al/Documents/Alu/alu
cp -n SprintMaster.png /Users/al/Documents/Alu/alu
cp -n SquirrelKing.png /Users/al/Documents/Alu/alu
cp -n SquishemSam.png /Users/al/Documents/Alu/alu
cp -n Stampede.png /Users/al/Documents/Alu/alu
cp -n Stanley.png /Users/al/Documents/Alu/alu
cp -n Stanley.png /Users/al/Documents/Alu/alu
cp -n StarShip.png /Users/al/Documents/Alu/alu
cp -n Steeplechase.png /Users/al/Documents/Alu/alu
cp -n StellarTrack.png /Users/al/Documents/Alu/alu
cp -n StreetRacer.png /Users/al/Documents/Alu/alu
cp -n SubmarineCommander.png /Users/al/Documents/Alu/alu
cp -n SundayFunday.png /Users/al/Documents/Alu/alu
cp -n SundayFunday.png /Users/al/Documents/Alu/alu
cp -n SuperActionBaseball.png /Users/al/Documents/Alu/alu
cp -n SuperActionBoxing.png /Users/al/Documents/Alu/alu
cp -n SuperActionFootball.png /Users/al/Documents/Alu/alu
cp -n SuperActionSoccer.png /Users/al/Documents/Alu/alu
cp -n SuperBaseball.png /Users/al/Documents/Alu/alu
cp -n SuperBreakout.png /Users/al/Documents/Alu/alu
cp -n SuperCrossForce.png /Users/al/Documents/Alu/alu
cp -n SuperFootball.png /Users/al/Documents/Alu/alu
cp -n SuperStarWars.png /Users/al/Documents/Alu/alu
cp -n SuperStarWars2.png /Users/al/Documents/Alu/alu
cp -n SuperStarWars3.png /Users/al/Documents/Alu/alu
cp -n Super_Birdie_Rush.png /Users/al/Documents/Alu/alu
cp -n Surround.png /Users/al/Documents/Alu/alu
cp -n SwitchbladeGenesis_Final.png /Users/al/Documents/Alu/alu
cp -n SwordQuestEarthworld.png /Users/al/Documents/Alu/alu
cp -n SwordQuestFireworld.png /Users/al/Documents/Alu/alu
cp -n SwordQuestWaterworld.png /Users/al/Documents/Alu/alu
cp -n Sword_of_Sodan_Piko_no_sega.png /Users/al/Documents/Alu/alu
cp -n Target-Renegade-U-_edited.png /Users/al/Documents/Alu/alu
cp -n Target-Renegade-U-_edited.png /Users/al/Documents/Alu/alu
cp -n TellyTurtle.png /Users/al/Documents/Alu/alu
cp -n Tempest.png /Users/al/Documents/Alu/alu
cp -n Tennis.png /Users/al/Documents/Alu/alu
cp -n Tetris.png /Users/al/Documents/Alu/alu
cp -n Tetris.png /Users/al/Documents/Alu/alu
cp -n Tg2_conn2.png /Users/al/Documents/Alu/alu
cp -n TheDamBuster.png /Users/al/Documents/Alu/alu
cp -n TheHeist.png /Users/al/Documents/Alu/alu
cp -n Threshold.png /Users/al/Documents/Alu/alu
cp -n Thunderbolt_II_PIKO_v5.png /Users/al/Documents/Alu/alu
cp -n Thunderbolt_final.png /Users/al/Documents/Alu/alu
cp -n Thunderbolt_final.png /Users/al/Documents/Alu/alu
cp -n Thwocker.png /Users/al/Documents/Alu/alu
cp -n TinHead.png /Users/al/Documents/Alu/alu
cp -n TomarcTheBarbarian.png /Users/al/Documents/Alu/alu
cp -n TopGear2.png /Users/al/Documents/Alu/alu
cp -n Topracer1.png /Users/al/Documents/Alu/alu
cp -n TournamentTennis.png /Users/al/Documents/Alu/alu
cp -n Treasure-Master-USA_edit.png /Users/al/Documents/Alu/alu
cp -n Treasure-Master-USA_edit.png /Users/al/Documents/Alu/alu
cp -n UPlay.png /Users/al/Documents/Alu/alu
cp -n Venture.png /Users/al/Documents/Alu/alu
cp -n Victory.png /Users/al/Documents/Alu/alu
cp -n VideoCheckers.png /Users/al/Documents/Alu/alu
cp -n VideoChess.png /Users/al/Documents/Alu/alu
cp -n VideoOlympics.png /Users/al/Documents/Alu/alu
cp -n VideoPinball.png /Users/al/Documents/Alu/alu
cp -n WarRoom.png /Users/al/Documents/Alu/alu
cp -n Warlords.png /Users/al/Documents/Alu/alu
cp -n WarpSpeedv3.png /Users/al/Documents/Alu/alu
cp -n Water_Margin_Final.png /Users/al/Documents/Alu/alu
cp -n WingWar.png /Users/al/Documents/Alu/alu
cp -n Wizard.png /Users/al/Documents/Alu/alu
cp -n WorldTrophySoccer.png /Users/al/Documents/Alu/alu
cp -n Yang_Warrior_Family_10_Oct_2016.png /Users/al/Documents/Alu/alu
cp -n YarsReturn.png /Users/al/Documents/Alu/alu
cp -n YarsRevenge.png /Users/al/Documents/Alu/alu
cp -n Zaombies.png /Users/al/Documents/Alu/alu
cp -n Zaxxon.png /Users/al/Documents/Alu/alu
cp -n ZeroTolerance.png /Users/al/Documents/Alu/alu
cp -n abaseb.png /Users/al/Documents/Alu/alu
cp -n actfancr.png /Users/al/Documents/Alu/alu
cp -n argus.png /Users/al/Documents/Alu/alu
cp -n astdelux.png /Users/al/Documents/Alu/alu
cp -n asteroid.png /Users/al/Documents/Alu/alu
cp -n astyanax.png /Users/al/Documents/Alu/alu
cp -n atarifb.png /Users/al/Documents/Alu/alu
cp -n avalnche.png /Users/al/Documents/Alu/alu
cp -n avspirit.png /Users/al/Documents/Alu/alu
cp -n baddudes.png /Users/al/Documents/Alu/alu
cp -n battroad.png /Users/al/Documents/Alu/alu
cp -n bbbxing.png /Users/al/Documents/Alu/alu
cp -n bchopper.png /Users/al/Documents/Alu/alu
cp -n bigrun.png /Users/al/Documents/Alu/alu
cp -n birdtry.png /Users/al/Documents/Alu/alu
cp -n bldwolf.png /Users/al/Documents/Alu/alu
cp -n boogwing.png /Users/al/Documents/Alu/alu
cp -n boomrang.png /Users/al/Documents/Alu/alu
cp -n brkthru.png /Users/al/Documents/Alu/alu
cp -n brubber.png /Users/al/Documents/Alu/alu
cp -n bsktball.png /Users/al/Documents/Alu/alu
cp -n btime.png /Users/al/Documents/Alu/alu
cp -n butasan.png /Users/al/Documents/Alu/alu
cp -n bwidow.png /Users/al/Documents/Alu/alu
cp -n bwings.png /Users/al/Documents/Alu/alu
cp -n cadanglr.png /Users/al/Documents/Alu/alu
cp -n canyon.png /Users/al/Documents/Alu/alu
cp -n castfant.png /Users/al/Documents/Alu/alu
cp -n cbuster.png /Users/al/Documents/Alu/alu
cp -n ccastles.png /Users/al/Documents/Alu/alu
cp -n centiped.png /Users/al/Documents/Alu/alu
cp -n cfghtice.png /Users/al/Documents/Alu/alu
cp -n cgraplop.png /Users/al/Documents/Alu/alu
cp -n chainrec.png /Users/al/Documents/Alu/alu
cp -n chameleo.png /Users/al/Documents/Alu/alu
cp -n chimerab.png /Users/al/Documents/Alu/alu
cp -n chinatwn.png /Users/al/Documents/Alu/alu
cp -n cischeat.png /Users/al/Documents/Alu/alu
cp -n citycon.png /Users/al/Documents/Alu/alu
cp -n clapapa.png /Users/al/Documents/Alu/alu
cp -n cluckypo.png /Users/al/Documents/Alu/alu
cp -n cmissnx.png /Users/al/Documents/Alu/alu
cp -n cnightst.png /Users/al/Documents/Alu/alu
cp -n cninja.png /Users/al/Documents/Alu/alu
cp -n comingsoon.png /Users/al/Documents/Alu/alu
cp -n compgolf.png /Users/al/Documents/Alu/alu
cp -n coozumou.png /Users/al/Documents/Alu/alu
cp -n cppicf.png /Users/al/Documents/Alu/alu
cp -n cprobowl.png /Users/al/Documents/Alu/alu
cp -n cprogolf.png /Users/al/Documents/Alu/alu
cp -n cptennis.png /Users/al/Documents/Alu/alu
cp -n cscrtry.png /Users/al/Documents/Alu/alu
cp -n csilver.png /Users/al/Documents/Alu/alu
cp -n cterrani.png /Users/al/Documents/Alu/alu
cp -n ctisland.png /Users/al/Documents/Alu/alu
cp -n cybattlr.png /Users/al/Documents/Alu/alu
cp -n darkseal.png /Users/al/Documents/Alu/alu
cp -n darwin.png /Users/al/Documents/Alu/alu
cp -n dassault.png /Users/al/Documents/Alu/alu
cp -n dbreed.png /Users/al/Documents/Alu/alu
cp -n dday.png /Users/al/Documents/Alu/alu
cp -n ddream95.png /Users/al/Documents/Alu/alu
cp -n desertwr.png /Users/al/Documents/Alu/alu
cp -n destroyr.png /Users/al/Documents/Alu/alu
cp -n disco.png /Users/al/Documents/Alu/alu
cp -n dominos.png /Users/al/Documents/Alu/alu
cp -n dorkeandymp.png /Users/al/Documents/Alu/alu
cp -n dragngun.png /Users/al/Documents/Alu/alu
cp -n dragon-view-modified.png /Users/al/Documents/Alu/alu
cp -n dragrace.png /Users/al/Documents/Alu/alu
cp -n drakkhen.png /Users/al/Documents/Alu/alu
cp -n edf.png /Users/al/Documents/Alu/alu
cp -n edrandy.png /Users/al/Documents/Alu/alu
cp -n exerion.png /Users/al/Documents/Alu/alu
cp -n exerizrb.png /Users/al/Documents/Alu/alu
cp -n exprraid.png /Users/al/Documents/Alu/alu
cp -n fcombat.png /Users/al/Documents/Alu/alu
cp -n ffantasy.png /Users/al/Documents/Alu/alu
cp -n fghthistu.png /Users/al/Documents/Alu/alu
cp -n fif.png /Users/al/Documents/Alu/alu
cp -n firetrk.png /Users/al/Documents/Alu/alu
cp -n formatz.png /Users/al/Documents/Alu/alu
cp -n fullthrottle.png /Users/al/Documents/Alu/alu
cp -n gallop.png /Users/al/Documents/Alu/alu
cp -n gondo.png /Users/al/Documents/Alu/alu
cp -n gourmet.png /Users/al/Documents/Alu/alu
cp -n gratia.png /Users/al/Documents/Alu/alu
cp -n gravitar.png /Users/al/Documents/Alu/alu
cp -n hachoo.png /Users/al/Documents/Alu/alu
cp -n hbarrel.png /Users/al/Documents/Alu/alu
cp -n hharry.png /Users/al/Documents/Alu/alu
cp -n hvysmsh.png /Users/al/Documents/Alu/alu
cp -n iganinju.png /Users/al/Documents/Alu/alu
cp -n immortal.png /Users/al/Documents/Alu/alu
cp -n ironcommando.png /Users/al/Documents/Alu/alu
cp -n jimpower.png /Users/al/Documents/Alu/alu
cp -n joemacr.png /Users/al/Documents/Alu/alu
cp -n kamikcab.png /Users/al/Documents/Alu/alu
cp -n karnovr.png /Users/al/Documents/Alu/alu
cp -n kazan.png /Users/al/Documents/Alu/alu
cp -n kchamp.png /Users/al/Documents/Alu/alu
cp -n kengo.png /Users/al/Documents/Alu/alu
cp -n kungfum.png /Users/al/Documents/Alu/alu
cp -n lastmisn.png /Users/al/Documents/Alu/alu
cp -n ldrun.png /Users/al/Documents/Alu/alu
cp -n ldrun2.png /Users/al/Documents/Alu/alu
cp -n ldrun3.png /Users/al/Documents/Alu/alu
cp -n ldrun4.png /Users/al/Documents/Alu/alu
cp -n legend_E_v3.png /Users/al/Documents/Alu/alu
cp -n liberate.png /Users/al/Documents/Alu/alu
cp -n liberatr.png /Users/al/Documents/Alu/alu
cp -n llander.png /Users/al/Documents/Alu/alu
cp -n lnc.png /Users/al/Documents/Alu/alu
cp -n lockload.png /Users/al/Documents/Alu/alu
cp -n loht.png /Users/al/Documents/Alu/alu
cp -n lomakai.png /Users/al/Documents/Alu/alu
cp -n lordofk.png /Users/al/Documents/Alu/alu
cp -n magdrop.png /Users/al/Documents/Alu/alu
cp -n magdrop2.png /Users/al/Documents/Alu/alu
cp -n magdrop3.png /Users/al/Documents/Alu/alu
cp -n majtitle.png /Users/al/Documents/Alu/alu
cp -n makaiden.png /Users/al/Documents/Alu/alu
cp -n meikyuh.png /Users/al/Documents/Alu/alu
cp -n metlclsh.png /Users/al/Documents/Alu/alu
cp -n mhavoc.png /Users/al/Documents/Alu/alu
cp -n midres.png /Users/al/Documents/Alu/alu
cp -n midresu.png /Users/al/Documents/Alu/alu
cp -n milliped.png /Users/al/Documents/Alu/alu
cp -n missile.png /Users/al/Documents/Alu/alu
cp -n montecar.png /Users/al/Documents/Alu/alu
cp -n mpatrol.png /Users/al/Documents/Alu/alu
cp -n mrbloopy.png /Users/al/Documents/Alu/alu
cp -n mspacman.png /Users/al/Documents/Alu/alu
cp -n mutantf.png /Users/al/Documents/Alu/alu
cp -n naughtyb.png /Users/al/Documents/Alu/alu
cp -n nitrobal.png /Users/al/Documents/Alu/alu
cp -n nob.png /Users/al/Documents/Alu/alu
cp -n nslasher.png /Users/al/Documents/Alu/alu
cp -n nslashers.png /Users/al/Documents/Alu/alu
cp -n nspirit.png /Users/al/Documents/Alu/alu
cp -n oscar.png /Users/al/Documents/Alu/alu
cp -n p47.png /Users/al/Documents/Alu/alu
cp -n p47aces.png /Users/al/Documents/Alu/alu
cp -n p47j.png /Users/al/Documents/Alu/alu
cp -n phantasm.png /Users/al/Documents/Alu/alu
cp -n pinbo.png /Users/al/Documents/Alu/alu
cp -n plusalph.png /Users/al/Documents/Alu/alu
cp -n pong.png /Users/al/Documents/Alu/alu
cp -n poolshrk.png /Users/al/Documents/Alu/alu
cp -n popflame.png /Users/al/Documents/Alu/alu
cp -n prosoccr.png /Users/al/Documents/Alu/alu
cp -n psychic5.png /Users/al/Documents/Alu/alu
cp -n pturn.png /Users/al/Documents/Alu/alu
cp -n redbaron.png /Users/al/Documents/Alu/alu
cp -n rodland.png /Users/al/Documents/Alu/alu
cp -n rtype.png /Users/al/Documents/Alu/alu
cp -n rtype2.png /Users/al/Documents/Alu/alu
cp -n rtypeleo.png /Users/al/Documents/Alu/alu
cp -n saturn.png /Users/al/Documents/Alu/alu
cp -n sbrkout.png /Users/al/Documents/Alu/alu
cp -n scudhamm.png /Users/al/Documents/Alu/alu
cp -n sdtennis.png /Users/al/Documents/Alu/alu
cp -n secretag.png /Users/al/Documents/Alu/alu
cp -n shackled.png /Users/al/Documents/Alu/alu
cp -n shootout.png /Users/al/Documents/Alu/alu
cp -n sidepckt.png /Users/al/Documents/Alu/alu
cp -n skydiver.png /Users/al/Documents/Alu/alu
cp -n skyfox.png /Users/al/Documents/Alu/alu
cp -n soccer.png /Users/al/Documents/Alu/alu
cp -n soccerkid.png /Users/al/Documents/Alu/alu
cp -n soldamj.png /Users/al/Documents/Alu/alu
cp -n spacduel.png /Users/al/Documents/Alu/alu
cp -n spelunkr.png /Users/al/Documents/Alu/alu
cp -n spinmast.png /Users/al/Documents/Alu/alu
cp -n spool3.png /Users/al/Documents/Alu/alu
cp -n sprint1.png /Users/al/Documents/Alu/alu
cp -n srdarwin.png /Users/al/Documents/Alu/alu
cp -n stadhero.png /Users/al/Documents/Alu/alu
cp -n stdragon.png /Users/al/Documents/Alu/alu
cp -n strhoop.png /Users/al/Documents/Alu/alu
cp -n stunt.png /Users/al/Documents/Alu/alu
cp -n supbtime.png /Users/al/Documents/Alu/alu
cp -n superbug.png /Users/al/Documents/Alu/alu
cp -n tempest.png /Users/al/Documents/Alu/alu
cp -n tetrisp.png /Users/al/Documents/Alu/alu
cp -n tetrisp2.png /Users/al/Documents/Alu/alu
cp -n topracer3000.png /Users/al/Documents/Alu/alu
cp -n travrusa.png /Users/al/Documents/Alu/alu
cp -n triothep.png /Users/al/Documents/Alu/alu
cp -n troangel.png /Users/al/Documents/Alu/alu
cp -n tron.png /Users/al/Documents/Alu/alu
cp -n tryout.png /Users/al/Documents/Alu/alu
cp -n tshingen.png /Users/al/Documents/Alu/alu
cp -n tshingna.png /Users/al/Documents/Alu/alu
cp -n tumblep.png /Users/al/Documents/Alu/alu
cp -n valtric.png /Users/al/Documents/Alu/alu
cp -n warlords.png /Users/al/Documents/Alu/alu
cp -n wizdfire.png /Users/al/Documents/Alu/alu
cp -n wndrplnt.png /Users/al/Documents/Alu/alu
cp -n xmultipl.png /Users/al/Documents/Alu/alu
cp -n zaviga.png /Users/al/Documents/Alu/alu
